[package]
name = "trenbet-subscription"
version = "0.1.0"
description = "TrenBet Subscription On-Chain Contract"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = "0.29.0"
