[toolchain]

[workspace]
members = [
    "programs/trenbet-escrow"
]
resolver = "2"

[features]
seeds = false
skip-lint = false

[programs.localnet]
trenbet_escrow = "FB1kJ1rQ8Uu5bdyKQBYYMGqJ8zEfVtcqTDLUTtyt3859"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lukegullekson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
